//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Call_of_Duty_Retriever.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Call_of_Duty_Retriever.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address: 18C49A4
        ///name: ping_increment
        ///type: int
        ///value: 25
        ///max: 500
        ///min: 1
        ///
        ///address: 18C49E8
        ///name: ping_default_min
        ///type: int
        ///value: 50
        ///max: 500
        ///min: 10
        ///
        ///address: 18C4A2C
        ///name: session_advertiseFailedSearchCount
        ///type: int
        ///value: 3
        ///max: 500
        ///min: 0
        ///
        ///address: 18C4A70
        ///name: com_maxfps
        ///type: int
        ///value: 60
        ///max: 1000
        ///min: 0
        ///
        ///address: 18C4AB4
        ///name: consoleGame
        ///type: string
        ///value: &quot;true&quot;
        ///
        ///address: 18C4AF8
        ///name: ps3Game
        ///type: string
        ///value: &quot;true&quot;
        ///
        ///address: 18C4B3C
        ///name: in_ps3myc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mw3 {
            get {
                return ResourceManager.GetString("mw3", resourceCulture);
            }
        }
    }
}
